### ISSUE TITLE
200, but code not send

### ISSUE THREAD

**Issue by DTPlayer** [lvoegl/ScIdClient#6]
Hello, when sending the code I receive HTTP 200, but the code itself is not sent to the email.
```python
import requests

headers = {
    'User-Agent': 'scid/4543 (Android; scroll-prod)',
    'Authorization': ''
}

data = {
    'lang': 'en',
    'email': '***',
    'remember': 'true',
    'game': 'scroll',
    'env': 'prod'
}

url = "https://id.supercell.com/api/ingame/account/login"

res = requests.post(url, data=data, headers=headers)

print(res.status_code)
print(res.text)
```

```bash
200
{"ok":true}
```

I pulled the request from the library. I will be glad for your help. Thanks in advance for your answer!

P.S:Data is not sent when using a server in Europe (Netherlands)

**Comment by lvoegl** [comment]
Seems like a duplicate of #3. I cannot control what the API does - as long as it returns code 200 and `{"ok":true}` the request is valid.

**Comment by DTPlayer** [comment]
Yes, I found a solution to the problem. It turned out that not all servers are suitable, and there is also a limit on sending letters)

**Comment by HouZzzz** [comment]
@DTPlayer
привет, есть какие то подробности о том, что не все сервера подходят? я попробовал около 20 зарубежных серверов из разных стран и ни на одном из них не работала отправка писем
